config:
  build:
    command: "npm run build"
    publish: "dist"
  redirects:
    - from: "/*"
      to: "/index.html"
      status: 200
    - from: "/about-us"
      to: "/about"
      status: 301
    - from: "/contact"
      to: "/contact-us"
      status: 301
